diff_drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: "left_wheel_joint"
  right_wheel: "right_wheel_joint"
  publish_rate: 50
  wheel_separation: 0.5         # Adjust based on your robot’s design
  wheel_radius: 0.1             # Adjust based on your robot’s design
  cmd_vel_timeout: 0.5
  use_stamped_vel: false
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
